In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

$(\theta_1 \times x) + (\theta_0 \times 1) = y_{predict}$


$y_{predict}$   gần bằng    $y_{actual}$

In [ ]:
X = np.array([[1], [2], [3], [4]])

In [ ]:
X

In [ ]:
y = np.dot(X, np.array([2.5])) + np.random.randn(4)

In [ ]:
y

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(X,y)

In [ ]:
X.shape

In [ ]:
linearModel = LinearRegression()

In [ ]:
linearModel.fit(X,y)

In [ ]:
y_predict = linearModel.predict(X) # ~ y_predict

In [ ]:
y_predict

In [ ]:
y

# Sử dụng MSE để tính **y_predict** vs **y**

In [ ]:
((y-y_predict)**2).mean()

In [ ]:
(abs(y-y_predict)).mean()

In [ ]:
theta_1 = linearModel.coef_
theta_0 = linearModel.intercept_

In [ ]:
theta_1

In [ ]:
theta_0

In [ ]:
X

In [ ]:
theta_1 * X + theta_0

# Hồi quy đa biến

In [1]:

from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
import numpy as np


X,y = fetch_california_housing(return_X_y=True)

In [2]:
X.shape

(20640, 8)

In [6]:
X[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [7]:
y[0]

4.526

In [3]:
linearModel = LinearRegression()

In [4]:
linearModel.fit(X,y)

LinearRegression()

In [8]:
y_predict = linearModel.predict(X)

In [9]:
y_predict

array([4.13164983, 3.97660644, 3.67657094, ..., 0.17125141, 0.31910524,
       0.51580363])

In [10]:
linearModel.coef_

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

In [11]:
linearModel.intercept_

-36.941920207184324

In [14]:
linearModel.predict([X[7]])

array([2.24668752])

In [ ]:
linearModel.predict([X[7]])

In [12]:
((y-y_predict)**2).mean()

0.5243209861846072